spring.application.name=calorie-manager-spring

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

logging.level.liquibase=DEBUG

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
