spring.application.name=calorie-manager-spring

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/calories
spring.datasource.username=postgres
spring.datasource.password=calorie
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
